// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX836hfK3oL1clxNC4WFJQifQ53_oRjV0',
    appId: '1:242037756353:web:9c5d83a530dce871971f40',
    messagingSenderId: '242037756353',
    projectId: 'cohousematch',
    authDomain: 'cohousematch.firebaseapp.com',
    storageBucket: 'cohousematch.firebasestorage.app',
    measurementId: 'G-SJECK63BYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAy7JOZjhPx_a4SfL1fDO5LfMNiBJ2RLc',
    appId: '1:242037756353:android:3f649e278a23f44b971f40',
    messagingSenderId: '242037756353',
    projectId: 'cohousematch',
    storageBucket: 'cohousematch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCuDtdsgipF-hGs7XvDxIaffvClKMogI',
    appId: '1:242037756353:ios:78657080e97a6700971f40',
    messagingSenderId: '242037756353',
    projectId: 'cohousematch',
    storageBucket: 'cohousematch.firebasestorage.app',
    iosBundleId: 'com.example.cohouseMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCuDtdsgipF-hGs7XvDxIaffvClKMogI',
    appId: '1:242037756353:ios:78657080e97a6700971f40',
    messagingSenderId: '242037756353',
    projectId: 'cohousematch',
    storageBucket: 'cohousematch.firebasestorage.app',
    iosBundleId: 'com.example.cohouseMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX836hfK3oL1clxNC4WFJQifQ53_oRjV0',
    appId: '1:242037756353:web:60b830bc58cf433f971f40',
    messagingSenderId: '242037756353',
    projectId: 'cohousematch',
    authDomain: 'cohousematch.firebaseapp.com',
    storageBucket: 'cohousematch.firebasestorage.app',
    measurementId: 'G-NY365T9FQ1',
  );
}
